version: '2'

services:

  rrshare:
    image: pundits/rrshareweb:v2.20
    ports:
      - "3001:3001"
    volumes:
      - ./data/rrshare64/output:/opt/work/rrshareweb/data
    environment:
      - TZ=Asia/Shanghai
    restart: always
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    networks:
      default:
        ipv4_address: ${IP_RANGE}.2

networks:
  default:
      driver: bridge
      ipam:
        config:
          - subnet: ${IP_RANGE}.0/24
            ip_range: ${IP_RANGE}.128/25
            gateway: ${IP_RANGE}.1